name: Release
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: nuuday/github-changelog-action@v1.0.1
        with:
          config_dir: ".chglog"
          filename: CHANGELOG.md
          next_version: "v0.0.1"
